// tailwind.config.js
const { fontFamily } = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "0.625rem",
        sm: "calc(0.625rem - 4px)",
        md: "calc(0.625rem - 2px)",
        lg: "0.625rem",
        xl: "calc(0.625rem + 4px)",
      },
      colors: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "oklch(0.55 0.22 263)",
        "primary-foreground": "oklch(0.985 0 0)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "#fff",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "oklch(0.708 0 0)",
        "chart-1": "oklch(0.646 0.222 41.116)",
        "chart-2": "oklch(0.6 0.118 184.704)",
        "chart-3": "oklch(0.398 0.07 227.392)",
        "chart-4": "oklch(0.828 0.189 84.429)",
        "chart-5": "oklch(0.769 0.188 70.08)",
        sidebar: "oklch(0.985 0 0)",
        "sidebar-foreground": "oklch(0.145 0 0)",
        "sidebar-primary": "oklch(0.205 0 0)",
        "sidebar-primary-foreground": "oklch(0.985 0 0)",
        "sidebar-accent": "oklch(0.97 0 0)",
        "sidebar-accent-foreground": "oklch(0.205 0 0)",
        "sidebar-border": "oklch(0.922 0 0)",
        "sidebar-ring": "oklch(0.708 0 0)",
        // Color aliases
        "color-background": "var(--background)",
        "color-foreground": "var(--foreground)",
        "color-card": "var(--card)",
        "color-card-foreground": "var(--card-foreground)",
        "color-popover": "var(--popover)",
        "color-popover-foreground": "var(--popover-foreground)",
        "color-primary": "var(--primary)",
        "color-primary-foreground": "var(--primary-foreground)",
        "color-secondary": "var(--secondary)",
        "color-secondary-foreground": "var(--secondary-foreground)",
        "color-muted": "var(--muted)",
        "color-muted-foreground": "var(--muted-foreground)",
        "color-accent": "var(--accent)",
        "color-accent-foreground": "var(--accent-foreground)",
        "color-destructive": "var(--destructive)",
        "color-border": "var(--border)",
        "color-input": "var(--input)",
        "color-ring": "var(--ring)",
        "color-chart-1": "var(--chart-1)",
        "color-chart-2": "var(--chart-2)",
        "color-chart-3": "var(--chart-3)",
        "color-chart-4": "var(--chart-4)",
        "color-chart-5": "var(--chart-5)",
        "color-sidebar": "var(--sidebar)",
        "color-sidebar-foreground": "var(--sidebar-foreground)",
        "color-sidebar-primary": "var(--sidebar-primary)",
        "color-sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "color-sidebar-accent": "var(--sidebar-accent)",
        "color-sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "color-sidebar-border": "var(--sidebar-border)",
        "color-sidebar-ring": "var(--sidebar-ring)",
      },
    container: {
      center: true,
      padding: "2rem",
    },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};