name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:  # Add this to enable manual triggering
jobs:
    build-and-deploy:
        name: Test, Build and Deploy
        runs-on: self-hosted
        environment: Production

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 22
              cache: 'npm'
              cache-dependency-path: | 
                backend/package-lock.json
                frontend/package-lock.json

        - name: Install Backend Dependencies
          working-directory: ./backend
          run: npm ci

        - name: Run Backend Tests
          working-directory: ./backend
          env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            PORT: ${{ secrets.PORT }}
          run: npm test
        
        - name: Deploy Backend changes
          if: success()
          working-directory: ./backend
          run: |
            echo "${{secrets.PROD}}" > .env
            pm2 reload backend || pm2 start backend
          
        - name: Install Frontend Dependencies
          working-directory: ./frontend
          run: npm ci
        
        - name: Build Frontend
          working-directory: ./frontend
          run: | 
           npm run build

        - name: Deploy application
          if: success() && (github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main'))
          run: |
            echo "${{ secrets.PROD }}" > ./backend/.env
            pm2 reload backend || pm2 start backend
            pm2 reload frontend || pm2 start frontend
            pm2 save